### ISSUE TITLE
error when closing app built with simpledisplay

### ISSUE THREAD

**Issue by ASHIT-AXAR** [adamdruppe/arsd#130]
"gui.d" is the name of myapp file, it's content is 

```d
// dmd example.d simpledisplay.d color.d
import arsd.simpledisplay;
import std.conv;

void main() {
	auto window = new SimpleWindow(Size(500, 500), "Event example - simpledisplay.d");

	int y = 0;

	void addLine(string text) {
		auto painter = window.draw();
		auto painter = window.draw();

		if(y + painter.fontHeight >= window.height) {
			painter.scrollArea(Point(0, 0), window.width,
			window.height, 0, painter.fontHeight);
			y -= painter.fontHeight;
		}

		painter.outlineColor = Color.blue;
		painter.fillColor = Color.blue;
		painter.drawRectangle(Point(0, y), window.width, painter.fontHeight);

		painter.outlineColor = Color.white;

		painter.drawText(Point(10, y), text);

		y += painter.fontHeight;
	}

	window.eventLoop(1000,
	  () {
		addLine("Timer went off!");
	  },
	  (KeyEvent event) {
		addLine(to!string(event));
	  },
	  (MouseEvent event) {
		addLine(to!string(event));
	  },
	  (dchar ch) {
		addLine(to!string(ch));
	  }
	);
}
```

`dmd gui.d simpledisplay.d color.d -L/subsystem:windows`

when i press close button i get this error
there is no error when compiling with no "-L/subsystem:windows" argument, but in this case a console is shown with gui

![simpledisplay](https://user-images.githubusercontent.com/24279964/35819597-63d69f9c-0ab8-11e8-97d4-59de81eae908.png)

**Comment by adamdruppe** [comment]
It works for me.... does it do it for you every time you run or just sometimes? I suspect it is the timer going off after the window is closed.

**Comment by ASHIT-AXAR** [comment]
yes it does every time i close it. 
that was my first try with this library, not important.
i'm trying other examples, everything ok.

`
// dmd example.d simpledisplay.d color.d
import arsd.simpledisplay;
void main() {
	auto window = new SimpleWindow(200, 200);
	{ // introduce sub-scope
		auto painter = window.draw(); // begin drawing
		/* draw here */
		painter.outlineColor = Color.red;
		painter.fillColor = Color.black;
		painter.drawRectangle(Point(0, 0), 200, 200);
	} // end scope, calling `painter`'s destructor, drawing to the screen.
	window.eventLoop(0); // handle events
}
`

really clean and easy to use library. thank you for your great works and arsd pack. :)

**Comment by ASHIT-AXAR** [comment]
hello adam
the same error with another example

import arsd.simpledisplay;

void main() {
	auto window = new SimpleWindow(400, 400);
	// every 100 ms, it will draw a random line
	// on the window.
	window.eventLoop(100, {
		auto painter = window.draw();

		import std.random;
		// random color
		painter.outlineColor = Color(uniform(0, 256), uniform(0, 256), uniform(0, 256));
		// random line
		painter.drawLine(
			Point(uniform(0, window.width), uniform(0, window.height)),
			Point(uniform(0, window.width), uniform(0, window.height)));

	});
}


when i set pulse timeout to 0, no error after closing the window
how can i dispose window and eventloop before exit ?

**Comment by adamdruppe** [comment]
On Wed, Feb 07, 2018 at 08:27:28AM +0000, ASHIT-AXAR wrote:
> when i set pulse timeout to 0, no error after closing the window
> how can i dispose window and eventloop before exit ?

You could call `.destroy(window);` at the end of main, but now I know it is definitely the timer going off at the end so I think I can fix it in general here, I'll work on it later today.

**Comment by ASHIT-AXAR** [comment]
> You could call `.destroy(window);` at the end of main, but now I know it is definitely the timer going off at the end so I think I can fix it in general here, I'll work on it later today.

thank you.

i tried both `.destroy(window);` and `window.destroy();` at the end of main. still getting the error.

**Comment by adamdruppe** [comment]
On Wed, Feb 07, 2018 at 06:38:35AM -0800, ASHIT-AXAR wrote:
> i tried both `.destroy(window);` and `window.destroy();` at the end of main. still getting the error.

ok must be the internal timer object then.


I'll get to it soon though, until then you can just ignore the error,
it is cleanup after the program is done.

**Comment by adamdruppe** [comment]
So I still couldn't make it error on my computer, so I had to guess as to what the fix might be.. I just pushed a new commit to the repo, can you try again with that little change and see if anything changed?

**Comment by adamdruppe** [comment]
I have a couple other ideas too but i wanna test this one first. Sorry for taking so long to get back to you, this has been a somewhat busy week.

**Comment by ASHIT-AXAR** [comment]
hello adam, i tried that and it still shows the error.
may using the old OS can cause the problem ? i use Windows 7 64.
there is no other system i can test on now

**Comment by ASHIT-AXAR** [comment]
i added a `try catch` to the code to see error but log file not creating.

```d
import arsd.simpledisplay;
import std.stdio;

void main() {
	try{
		auto window = new SimpleWindow(400, 400);
		// every 100 ms, it will draw a random line
		// on the window.
		window.eventLoop(100, {
			auto painter = window.draw();
			import std.random;
			// random color
			painter.outlineColor = Color(uniform(0, 256), uniform(0, 256), uniform(0, 256));
			// random line
			painter.drawLine(
				Point(uniform(0, window.width), uniform(0, window.height)),
				Point(uniform(0, window.width), uniform(0, window.height)));
		});
	}
	catch(Exception e){
		auto f = File("log.txt", "r+");
		f.writeln(e.message);
		f.close();
	}
}
```

**Comment by adamdruppe** [comment]
On Thu, Feb 08, 2018 at 04:56:07AM +0000, ASHIT-AXAR wrote:
> i added a `try catch` to the code to see error but log file not creating.

first it is probably an Error rater than an Exception you need to catch

but second I am quite sure this is happening outside main, when the runtime tries to cleanup.

**Comment by adamdruppe** [comment]
I just pushed another possible fix... try again plz

**Comment by ASHIT-AXAR** [comment]
thank you.
works well now. there is no error anymore.

**Comment by ASHIT-AXAR** [comment]
one more question: i tried minigui.d
i was looking at simple elements like: Button, Label, imagebox (maybe set and get pixels) 
i didn't find anyway in button element to change its label during runtime. in Label i can change label_ and call redraw(), but i didn't find something similar for Button (not so important at this point)
i think the only way to show a picture (rather than drawing as window background) is to create a new SimpleWindow and show that ?

**Comment by adamdruppe** [comment]
On Thu, Feb 08, 2018 at 02:17:41PM -0800, ASHIT-AXAR wrote:
> i didn't find anyway in button element to change its label during runtime. in Label i can change label_ and call redraw(), but i didn't find something similar for Button (not so important at this point)

Yeah, I never implemented that but someone emailed me a patch last week and I just forgot to merge it. Added now, you can do `button.label = "whatever";`

> i think the only way to show a picture (rather than drawing as window background) is to create a new SimpleWindow and show that ?

You can draw in custom Widgets too by overriding `paint` or calling the `draw`
method on it, similar to a full SimpleWindow.

I don't think I ever implemented an ImageBox class but it wouldn't be too hard.

**Comment by ASHIT-AXAR** [comment]
very well.
yesterday i try to add ImageBox.  ![emoji-dandon](https://user-images.githubusercontent.com/24279964/36059254-ddb7a768-0e49-11e8-9582-30a7709f91dc.png)


```d
class ImageBox : Widget {
	import arsd.png;
	
	private int width_ = 32;
	private int height_ = 32;
	private Image image_;
	override int minHeight() { return this.height_; }
	override int minWidth() { return this.width_; }

	this(Widget parent = null) {
		this.tabStop = false;
		super(parent);
	}

	public void setImage(string filename){
		this.image_ = Image.fromMemoryImage(readPng(filename));
		this.width_ = image_.width;
		this.height_ = image_.height;
		redraw();
	}

	public void setImage(Image image){
		this.image_ = image;
		this.width_ = image_.width;
		this.height_ = image_.height;
		redraw();
	}

	public Image getImage(){ return this.image_; }

	override void paint(ScreenPainter painter) {
		version(custom_widgets)
		draw3dFrame(this, painter, FrameStyle.sunk, Color.white);
		painter.drawImage(Point(4, 4), this.image_);
	}
}
```

but now i think i would be of no help !   ![emoji-khejalat](https://user-images.githubusercontent.com/24279964/36059263-0347cc9c-0e4a-11e8-9660-ceb5f1300df0.png)
